name: rastreador_gt06
description: Simulador de Rastreador GT06 - Cliente Traccar com Arduino

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # GPS e Localização
  geolocator: ^13.0.2
  
  # USB Serial para Arduino
  usb_serial: ^0.5.2
  
  # Estado e UI
  provider: ^6.1.2
  
  # Utilidades
  shared_preferences: ^2.5.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/
